### PR TITLE
Fixed sequence and added support for arbitrary depth

### PR DESCRIPTION
**Pull request by isaacmorneau**
I really just felt like it so here's a PR :)

### CODE REVIEW

**Comment by dodie** [comment]
Hi @isaacmorneau !

Thanks for the contribution!

> added support for arbitrary depth

Looks nice!

> Fixed sequence

How so? I've checked the original plugin and this PR, they seem to produce identical results.

Additionally, the `s:fiboIndent` now contains an exact same extra `[1, 0]` as a second element which is not good, because this array will be converted to a dict later. This means that this value is dropped (because of the [1,1], which is necessary) and now we only have 14 indent levels.

Could you please modify the code to not include this extra element and preserve the original items? Thanks!

**Comment by isaacmorneau** [comment]
Sure thing, I totally glazed over the fact its converted to a dictionary afterward. I only thought, "hold on the fib sequence contains two '1's" and didn't consider it would ignored right afterward.

**Comment by isaacmorneau** [comment]
In retesting it I did find that the final position `[610, 975]` in yours is computed as `[610, 986]` in mine. I doubled checked and I believe that it should be 986, can you confirm?

Cheers,

**Comment by dodie** [comment]
Yes, 986 seems fine, I think I messed up the original version. Thanks for checking!

I just tried the new version and it starts with the following script error:

> E121: Undefined variable: s:FiboMaxDepth
> E15: Invalid expression: s:i < s:FiboMaxDepth

Could you please check that out?

**Comment by isaacmorneau** [comment]
It was a typo from debugging. Fixed now

**Comment by dodie** [comment]
Awesome!

**Pull request merged**
